# Railway Nixpacks configuration
# Node 16.x as defined in package.json engines and .nvmrc

[phases.setup]
nixPkgs = ["nodejs-16_x", "npm-8_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
